### ISSUE TITLE
consider making an commend option

### ISSUE THREAD

**Issue by Misjudgments** [den0un/CsgoReportBot#2]
would be cool to have a commend & report bot 
@den0un

**Comment by den0un** [comment]
i had an idea but im not that good at coding.
what i know on commend is the only way to do it is when you are online on a server with somone to commend you,
so if we can launch multiple windows of csgo in a sandbox (isolated from each other) and we make them commend somone it will be a good project

**Comment by Misjudgments** [comment]
@den0un i hope one day you'll make it.
