### ISSUE TITLE
Error, could not login: Please verify your humanity by re-entering the characters in the captcha.

### ISSUE THREAD

**Issue by Misjudgments** [den0un/CsgoReportBot#3]
![image](https://user-images.githubusercontent.com/88270832/128096943-d82a8add-7ec1-40c2-a8b6-363276766cb6.png)
tried to run 25 accounts and this error happend, to solve this you need to add an proxy option.
please fix.
@den0un

**Comment by 7ua** [comment]
@den0un this is pretty easy list the proxies in a dictionary then loop through them untill one connects

**Comment by 7ua** [comment]
@Misjudgments Sure though could you star this repo first? https://github.com/7ua/Moon/

**Comment by Misjudgments** [comment]
@7ua  dunno what it does but i clicked on the star icon

**Comment by den0un** [comment]
> ![image](https://user-images.githubusercontent.com/88270832/128096943-d82a8add-7ec1-40c2-a8b6-363276766cb6.png)
> tried to run 25 accounts and this error happend, to solve this you need to add an proxy option.
> please fix.
> @den0un

tbh i got lazy testing proxies and coding it like that but here is a quick fix...
i had that problem before when i was trying the login process, if im not wrong this error appears when you login with wrong credentials, so check your accounts maybe one of the passwords/usernames are wrong, when i corrected the mistakes this problem never appeared again.

**Comment by 7ua** [comment]
> > ![image](https://user-images.githubusercontent.com/88270832/128096943-d82a8add-7ec1-40c2-a8b6-363276766cb6.png)
> > tried to run 25 accounts and this error happend, to solve this you need to add an proxy option.
> > please fix.
> > @den0un
> 
> tbh i got lazy testing proxies and coding it like that but here is a quick fix...
> i had that problem before when i was trying the login process, if im not wrong this error appears when you login with wrong credentials, so check your accounts maybe one of the passwords/usernames are wrong, when i corrected the mistakes this problem never appeared again.

Perhaps ratelimited?

**Comment by Misjudgments** [comment]
@7ua Misjudgments#2320
also, @den0un it wasn't the case, from what I understand I sent too many requests it actually blocked me from visiting the steam profile I tried to bot.
so I think it just blocks the IP after 20 or more requests

**Comment by 7ua** [comment]
@Misjudgments sent
Also you probably got ratelimited

**Comment by Misjudgments** [comment]
@7ua accepted you

**Comment by den0un** [comment]
i think thats why the code did work fine for me , i used only 9 accounts.

**Comment by Misjudgments** [comment]
@den0un so? cause rn the bot is kinda useless, 25 max reports are nothing, I suggest you try to find a solution for that, I would have helped if I could but again, I don't even know the basics. 

if you don't want to add it please @ me and tell me, so I'll know to keep looking myself for an answer
