### ISSUE TITLE
consider changing log in system to user:pass

### ISSUE THREAD

**Issue by Misjudgments** [den0un/CsgoReportBot#4]
would be easier if you can change it to username:password format, 
so like in a folder that named accounts.txt:
misjudgments123(username):misjud321123(password)
then it would split it into 2:
with open('accounts.txt', 'r') as file:
   for details in file:
        username, password = details.split(':')
      
tried it myself but I am an inexperienced coder in python so I think if you can try to do this it would be really great
thank you :)
@den0un

**Comment by den0un** [comment]
@Misjudgments yes it would be but im not experienced too i did what i learned,
if we look at it from another side, coding it with a database will be much more managable but not everyone have a database on their OS so i tried to make it as simple as i can

**Comment by den0un** [comment]
@Misjudgments thanks for the help i upgraded the code like you said.
